<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<UseWinUI>true</UseWinUI>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>J4JSoftware.WindowsUtilities</AssemblyName>
		<RootNamespace>J4JSoftware.WindowsUtilities</RootNamespace>
		<Authors>Mark A. Olbert</Authors>
		<Company>Jump for Joy Software</Company>
		<Product>J4JSoftware Windows utilities</Product>
		<Description>provides utilities for Windows Apps (WinUI 3)</Description>
		<Copyright>© Mark A. Olbert all rights reserved</Copyright>
		<Version>1.2.0.0</Version>
		<AssemblyVersion>1.2.0.0</AssemblyVersion>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/markolbert/WindowsUtilities</RepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<PackageReleaseNotes>add geometric transform methods, updated to Net9</PackageReleaseNotes>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
		<PackageLicenseFile>license.md</PackageLicenseFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.4" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.7.250401001" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.1742" />
		<PackageReference Include="Serilog.Extensions.Logging" Version="9.0.1" />
	</ItemGroup>

</Project>
